# Generated by Django 5.2.8 on 2026-01-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-email',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
