# Generated by Django 5.2.8 on 2025-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optional human-friendly name for the generated report (e.g., 'Alice - Sep 2025').", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateField(blank=True, help_text='Optional start date filter (inclusive).', null=True)),
                ('date_to', models.DateField(blank=True, help_text='Optional end date filter (inclusive).', null=True)),
                ('status', models.CharField(blank=True, choices=[('', 'All'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='', max_length=20)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ('-created_at',),
            },
        ),
    ]
