# Generated by Django 5.2.8 on 2025-11-28 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who generated the report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='filter_user',
            field=models.ForeignKey(blank=True, help_text='Optional: filter tasks by this assignee/user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filtered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
